import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/features/Sidebar";
import AuthProvider from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en" data-theme="dark">
        <body className={inter.className}>
          <div className="flex h-screen bg-base-300">
            <div className="overflow-y-auto shrink-0 flex items-center bg-base-100">
              <Sidebar />
            </div>
            <div className="grow overflow-y-auto">{children}</div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
